const puzzleNames = [
	['fillomino-hex', ['fillomino (hex)']],
	['mastermind-nurikabe-yajilin', ['mastermind-nurikabe-yajilin']],
	['snakes', ['snakes', 'paths: snakes']],
	['yajilin-hex', ['六角ループであろー', 'yajilin (hex)']],
	['numbersnake-diagonal', ['number snake (diagonal)']],
	['find5pairs', ['find 5 pairs']],
	['inversetetorominodivision', ['逆ヒントテトロミノ分割']],
	['findthematchingsets', ['find the matching sets']],
	['skyscrapers-multiview', ['multiview skyscrapers']],
	['allorone', ['all or one']],
	['heyawake-irregular', ['heyawake (irregular)']],
	['skyscrapers-park', ['skyscrapers (park)']],
	['sunglasses', ['サングラス', 'sunglasses']],
	['snake-length', ['snake (length, ends)']],
	['spolicy', ['spolicy']],
	['crackiton', ['crack it on']],
	['thermometers-iso', ['thermometers (iso)']],
	['yinyang-equalregions', ['yin-yang (equal regions)']],
	['easyas-kunekune', ['くねくねabcプレース', 'くねくねabcdプレース']],
	['hexa7', ['hexa 7']],
	['pentominorelations', ['pentomino relations']],
	['japanese-railway', ['japanese railway']],
	['coins', ['coins']],
	['compass', ['compass']],
	['tangledwords1', ['アロージグザグクロス']],
	['starbattle', ['スターバトル', 'star battle', 'objects: star battle']],
	['japanesesums-hex', ['japanese sums (hex)', 'japanese sums']],
	['gaps-notouch', ['gaps (no touch)', 'star gaps', 'gaps', 'b. gaps (no touch)']],
	['nurikabe-norect', ['四角禁止の間■仕■切■り']],
	['inaiinaiba', ['いないいないバー']],
	['yajilin-regions', ['ヘヤジリン', 'yajilin (regions)']],
	['hitori-letter', ['letter hitori']],
	['shikaku-unknowns', ['?入りナンバーエリア']],
	['tasquare', ['たすくえあ', 'tasquare']],
	['skyscrapers-relations', ['skyscrapers (relations)']],
	['japanesesums', ['japanese sums']],
	['tapa-lits', ['tapa (lits)']],
	['doppelblock-diagonals', ['doppelblock (diagonals)']],
	['paradesums', ['parade sums']],
	['wordsearch-count', ['word search (count)']],
	['nurikabe-battleships', ['nurikabe battleships']],
	['aidabeya', ['相ダ部屋']],
	['darts', ['darts']],
	['doppelblock-variable', ['doppelblock (variable)']],
	['pentominous-borders', ['pentominous (borders)']],
	['vama', ['vama']],
	['cave', ['バッグ', 'cave']],
	['products-antiknight', ['products (antiknight)']],
	['codeddivision', ['ノータッチ覆面分割']],
	['easyas-japanese-railways', ['easy as japanese railways']],
	['shikaku-offbyone', ['嘘つきナンバーエリア', 'shikaku (off-by-one)']],
	['products-offbyone', ['products (off-by-one)']],
	['wolvesandsheep', ['ヤギとオオカミ', 'goats and wolves']],
	['snake-offbyone', ['嘘つきスネーク']],
	['pentoblokus', ['pento-blokus']],
	['easyas-loop', ['easy as (loop)']],
	['primepath', ['prime path']],
	['doppelblock-bigcells', ['irregular doppelblock']],
	['anglers', ['anglers']],
	['kuromasu-product', ['kuromasu (product)']],
	['columndance', ['column dance']],
	['skyscrapers-x', ['中庭ビルディング']],
	['doppelblock-parquetliar', ['doppelblock (parquet, liar)']],
	['kakuro-fillin', ['フィルインサムクロス']],
	['tetromino-division', ['tetromino division']],
	['slitherlink-dual', ['似て非なるループメーカー']],
	['yinyang', ['しろまるくろまる', 'yin-yang']],
	['snake-striped', ['snake (ends,striped)']],
	['pillboxes', ['pillboxes']],
	['pills-hex', ['pills (hex)', 'pills']],
	['blokus', ['blokus', 'blokus (tetriminoes)', 'blokus (pentominoes)']],
	['fillintheblanks', ['what\'s next?', 'fill in the blanks']],
	['skyscrapers-bigcells', ['skyscrapers (big cells)']],
	['sums', ['sums']],
	['easyas', ['abcプレース', 'easy as...', 'easy as']],
	['slidingblocks', ['sliding blocks']],
	['numberparades', ['number parades']],
	['fillomino-nonconsective', ['不連続な隣人']],
	['anglers-cave', ['anglers’ cave']],
	['suguru', ['suguru']],
	['snake-pit', ['snake pit']],
	['swisscrosses2color', ['swiss crosses (2-color)']],
	['indexsums', ['index sums']],
	['crisscross-unknowns', ['虫食いスケルトン']],
	['shapesweeper', ['shapesweeper']],
	['futoshiki-hex', ['futoshiki (hex)']],
	['battleships', ['バトルシップ', 'battleships']],
	['cave-bigcells', ['cave (big cells)']],
	['chessattacks', ['chess attacks']],
	['minesweeper', ['ボンバーパズル', 'minesweeper']],
	['fourwinds-encoded', ['覆面ウォールロジック']],
	['skyscrapers', ['ビルディングパズル', 'ビルディング', 'skyscrapers']],
	['sixwinds', ['six winds']],
	['ayda', ['ayda']],
	['shikaku', ['四角に切れ', 'shikaku', 'regions: shikaku']],
	['elasticwords', ['elastic words']],
	['footballpass', ['football pass']],
	['slitherlink-wolvesandsheep', ['slitherlink (wolves and sheep)']],
	['arithmeticsquare-encoded', ['arithmetic square (encoded)', 'arithmetic square (encrypted)']],
	['kuromasu-starbattle', ['kuromasu (star battle)']],
	['sky-tomtom', ['skytomtom']],
	['slant', ['ごきげんななめ', 'ループはいやよ', 'slalom']],
	['shortestdistances', ['shortest distances']],
	['slitherlink-unequallengths', ['slitherlink (unequal lengths)']],
	['nofourinarow-overlapping', ['no four in a row (overlapping)']],
	['walls', ['walls']],
	['lakes', ['lakes', 'shading: lakes']],
	['latinsquare', ['ラテンスクエア']],
	['adjacencysums', ['adjacency sums']],
	['palindromesornot', ['palindromes or not']],
	['hashiwokakero-encoded', ['hashiwokakero (encoded)', 'encrypted hashiwokakero']],
	['balance', ['balance']],
	['slitherlink-bigcells', ['slitherlink (big cells)']],
	['shakashaka', ['シャカシャカ', 'shakashaka']],
	['dosokuloop', ['同側ループ']],
	['lightandshadow', ['light and shadow']],
	['gaps-notouch-offbyone', ['gaps (no touch, off by one)']],
	['arithmeticsquare-unknownresults', ['arithmetic square (unknown results)']],
	['endpoints', ['endpoints']],
	['simultaneous-equations', ['小町算', 'simultaneous equations']],
	['yajilin', ['ヤジリン', 'ループであろー', 'yajilin']],
	['nurikabe-snake', ['nurikabe (snake)']],
	['cave-inorout', ['内外不明のcave']],
	['hiroimono', ['碁石拾い', 'hiroimono']],
	['thermometers-hex', ['thermometers (hex)']],
	['snake-three', ['3匹のスネーク']],
	['l', ['える']],
	['nuraf', ['nuraf']],
	['nurikabe-symmetry', ['nurikabe (symmetry)']],
	['letterbags', ['letter bags']],
	['simpleloop-shaded', ['loop (shaded)']],
	['clouds', ['clouds', 'rain clouds']],
	['tomtom-operations', ['tomtom (operations)', 'numbers: tomtom operations', 'tom tom (operations)']],
	['loop-tapa', ['loop (tapa)']],
	['kropki-hex', ['kropki (hex)', 'kropki']],
	['masyu-notouch', ['no-touch masyu', 'loop: no-touch masyu']],
	['parkinglot', ['パーキング', 'parking lot']],
	['snake-stripedlengthends', ['snake (striped, length, ends)']],
	['jigsawpuzzle', ['jigsaw puzzle']],
	['slitherlink', ['スリザーリンク', 'ループメーカー', 'slitherlink']],
	['yajilin-iso', ['yajilin (iso)']],
	['skyscraper-blocks', ['skyscraper blocks']],
	['myopia', ['myopia']],
	['fillomino-iso', ['fillomino (iso)']],
	['battleships-indexsums', ['battleships (index sums)']],
	['wordsearch', ['シークワード', 'word search', 'wordsearch']],
	['tripletsums', ['triplet sums']],
	['fourwinds', ['ウォールロジック', 'four winds']],
	['maxloop', ['最大値ループ']],
	['inverselitso', ['inverse litso']],
	['hidato', ['hidato']],
	['arrow-latinsquare', ['arrow latin square']],
	['kakuro-grouping', ['大中小サムクロス']],
	['lits', ['lits', 'テトロミノリンク']],
	['scrabble', ['セルフスケルトン', '親切なセルフスケルトン', 'scrabble', 'scrabble (letters)', 'scrabble (multiple letters)', 'scrabble (unused word)']],
	['wasyas-hex', ['easy as (hex)', 'easy as...']],
	['slitherlink-fullevens', ['slitherlink (full evens)']],
	['slashpack', ['slash pack']],
	['yajilin-castlewall', ['yajilin (castle wall)']],
	['inequalities', ['inequalities']],
	['baca-givenset', ['baca (given set)']],
	['dominion', ['dominion']],
	['slitherlink-hex', ['六角ループメーカー', 'slitherlink', 'slitherlink (hexagonal)']],
	['gaps', ['gaps', 'objects: gaps']],
	['arithmeticsquare-unassigned', ['arithmetic square (unassigned)']],
	['fillomino-bigcells', ['fillomino (big cells)']],
	['scrabble-2crossings', ['scrabble (2+ crossings)']],
	['balancescales', ['balance scales']],
	['makeamaze', ['make a maze']],
	['easyas-lits', ['easy as lits']],
	['paintbynumbers-some', ['paint by some numbers']],
	['pentominoareas', ['ペントミノエリア']],
	['spiralgalaxies-tetrominoes', ['spiral galaxies + tetrominoes', 'spiral galaxies (tetrominoes)']],
	['counttheshapes', ['count the shapes']],
	['doppelblock-unknownset', ['doppelblock (unknown set)']],
	['masyu-singleliar', ['masyu (single liar)']],
	['kakuro-nonconsective', ['不連続サムクロス']],
	['fourwinds-toroidal', ['シームレスウォールロジック']],
	['oldmaid', ['old maid']],
	['alphabetblocks', ['alphabet blocks']],
	['slitherlink-pentominoes', ['slitherlink (pentominoes)']],
	['yajilin-rows', ['rows yajilin', 'loop: rows yajilin']],
	['shikaku-spiralgalaxies', ['四角か対称か']],
	['productlines', ['product lines']],
	['tictaclogic', ['tic-tac-logic']],
	['baca', ['baca']],
	['teraxx', ['tera xx']],
	['cryptarithm', ['虫食い算', 'arithmetic separation']],
	['shikaku-encoded', ['覆面ナンバーエリア']],
	['crisscross-crowded', ['criss-cross (crowded)']],
	['tapa-transparent', ['tapa (transparent)']],
	['sudoku', ['数独', 'ナンプレ', 'sudoku']],
	['ripplearrows', ['ripple arrows']],
	['japanese-snake', ['japanese snake (ends)']],
	['skyscrapers-connected', ['ビルディングの輪']],
	['kakuro-parity', ['偶か奇かサムクロス']],
	['trid', ['trid']],
	['magnets-toroidal', ['magnets (toroidal)']],
	['pentominoes', ['ペントミノプレース']],
	['shakashaka-encoded', ['覆面シャカシャカ', 'shakashaka (encoded)']],
	['endpoints-hex', ['endpoints (hex)']],
	['araf', ['araf']],
	['skyscrapers-shapes', ['shapeskyscrapers']],
	['futoshiki', ['futoshiki']],
	['castlewall', ['castle wall']],
	['crossranges', ['crossranges']],
	['mastermind', ['mastermind']],
	['doublechoco', ['ダブルチョコ', 'double choco']],
	['letterweights', ['覆面サム', 'letter weights']],
	['skyscraper-sums', ['skyscraper sums']],
	['loopportals', ['loop (portals)']],
	['hexiom', ['hexiom']],
	['futoshiki-iso-sudoku', ['futoshiki (iso, sudoku)']],
	['findthedifferences', ['find the differences']],
	['tapa-wall', ['tapa (wall)']],
	['binary-parquet', ['binary parquet']],
	['skyscrapers-encoded', ['覆面ビルディングパズル', 'skyscrapers (encoded)']],
	['rook-hidato', ['rook hidato']],
	['capsules', ['capsules']],
	['paintbynumbers-blackorwhite', ['paint by numbers (black or white)']],
	['arrows', ['arrows']],
	['battleships-phrase', ['battleships (phrase)']],
	['maxiloop', ['maxi loop']],
	['postits', ['post-its']],
	['easyas-iso', ['easy as (iso)', 'easy as... (iso)']],
	['akari', ['美術館', 'bulbs (akari)', 'akari']],
	['easyas-fuzuli', ['easy as (fuzuli)', 'easy as... (fuzuli)']],
	['hungarian-numberlink', ['hungarian numberlink']],
	['recto', ['recto']],
	['pentominous-spiralgalaxies', ['pentominous (spiral galaxies)']],
	['shapedivision', ['shape division']],
	['commonletters', ['common letters']],
	['trianglewordsearch', ['triangle word search']],
	['arithmeticsquare', ['クロスマッス', '吉例クロスマッス', 'arithmetic square', 'numbers: arithmetic square']],
	['hundred', ['hundred']],
	['doppelblock-2', ['ビトィーン2サム']],
	['fillintheblank', ['fill in the blank']],
	['japanese-columndance', ['japanese column dance']],
	['swisscrossessum', ['swiss crosses (sum)']],
	['pentopia', ['pentopia', 'pentominoes (myopia)']],
	['minesweeper-encoded', ['覆面ボンバーパズル']],
	['pyramid', ['ピラミッド']],
	['ilus', ['ilus']],
	['skyscrapers-uncounted', ['uncounted skyscrapers']],
	['esayas-v1', ['注文の多いabcプレース']],
	['numbersnake-orthogonal', ['number snake (orthogonal)']],
	['brokencalculator', ['broken calculator']],
	['heyawake', ['へやわけ', 'heyawake']],
	['slitherlink-noswiss', ['slitherlink (no swiss)']],
	['magnets-horseshoes', ['magnets (horseshoes)']],
	['wordtsunagi', ['ワードつなぎ']],
	['hashiwokakero', ['橋をかけろ']],
	['division', ['ブロック分割', 'pentomino division']],
	['magnets-diagonal', ['magnets (diagonal)']],
	['squaredivision', ['square division']],
	['characterbattle', ['character battle']],
	['rippleeffect', ['波及効果', 'ripple effect']],
	['nanro-yinyang', ['nanro signpost (yin-yang)']],
	['easyas-second', ['easy as (second)']],
	['tomtom', ['tomtom', 'numbers: tomtom', 'tom tom']],
	['darkknightlines', ['dark knightlines']],
	['pointingatthecrowd', ['pointing at the crowd']],
	['pentominous', ['ノータッチ・ペントミノ分割', 'pentominous']],
	['spiralgalaxies-battleships', ['spiral galaxies + battleships']],
	['japanese-honeyislands', ['ハニーアイランド', 'japanese honey islands']],
	['statuepark-noreflection', ['statue park (no reflection)']],
	['yajinurikabelin', ['yajinurikabelin']],
	['topheavy', ['頭でっかちナンプレ', 'top heavy']],
	['matches', ['matches']],
	['minesweeper-pills', ['ダイナマイトパズル', 'minesweeper (pills)']],
	['battleships-hex', ['battleships (hex)']],
	['doppelblock-set-diagonals', ['doppelblock (set, diagonals)']],
	['chains', ['chains']],
	['japanese-parkinglot', ['japanese parking lot']],
	['kropki', ['kropki']],
	['counttheknightpaths', ['count the knight paths']],
	['snake-myopia', ['snake (myopia)']],
	['arithmeticsquare-withzero', ['arithmetic square with zero']],
	['arukone-cross', ['arukone with crossings']],
	['hexislands', ['hex islands']],
	['snakystationloop', ['snaky station loop']],
	['yinyang-noswiss', ['yin-yang (no swiss)']],
	['nanro', ['ナンロー', 'nanro', 'nanro signpost']],
	['loop-pentominowalls-maxlengths', ['loop (pentomino walls, max lengths)']],
	['paintbynumbers', ['お絵かきロジック']],
	['products', ['products']],
	['lits-tapa', ['lits (tapa)']],
	['tetroscope', ['tetroscope']],
	['spans', ['spans']],
	['kurotto', ['クロット', 'kurotto']],
	['fillomino-futoshiki', ['fillomino (futoshiki)']],
	['passwordpath', ['password path']],
	['hydra', ['hydra']],
	['kakuro', ['カックロ', 'サムクロス', 'kakuro']],
	['japanesesums-hitori', ['japanese sums (hitori)', 'tapa']],
	['masyu-colorblind', ['masyu (colorblind)']],
	['coral-overlapping', ['coral (overlapping)']],
	['starbattle-halfregion', ['half-region star battle', 'objects: half-region star battle']],
	['oases', ['oases']],
	['slitherlink-outliars', ['slitherlink (out-liars)']],
	['snake', ['スネーク', 'snake', 'paths: snake', 'snake (with ends)', 'snake (ends)']],
	['differentneighbors', ['different neighbors']],
	['simpleloop', ['シンプルループ', 'simple loop', 'loop: simple loop', 'loop']],
	['skyscraper-nurikabe', ['skyscraper nurikabe', 'shading: skyscraper nurikabe']],
	['skyscrapers-diagonal', ['skyscrapers (diagonal)', 'skyscrapers with diagonals']],
	['easyas-hex', ['easy as (hex)', 'easy as... (hex)']],
	['skyscrapers-irregular', ['幾何学ビルディング']],
	['skyscrapers-fullevens', ['skyscrapers (full evens)']],
	['snakyloop-regions', ['snaky loop (regions)']],
	['fuzuli', ['fuzuli']],
	['abba', ['abba']],
	['fillomino', ['フィルオミノ', 'fillomino', 'regions: fillomino']],
	['tents-diagonaltwos', ['tents (diagonal, twos)']],
	['masyu-colorblind-yajilin', ['masyu (colorblind) + yajilin']],
	['masyu-blackened-alternating', ['masyu (blackened, alternating)']],
	['yajilin-minesweeper', ['yajilin (minesweeper)']],
	['litso', ['litso']],
	['modes', ['modes']],
	['doppelblock', ['ビトィーンサム', 'doppelblock']],
	['yajilin-battleships', ['yajilin (battleship)', 'yajilin (battleships)']],
	['fillomino-123', ['fillomino (123)']],
	['doppelblock-skyscrapers', ['doppelblock skyscrapers']],
	['tetrominous', ['tetrominous']],
	['honeyislands', ['ハニーアイランド', 'honey islands']],
	['nurikabe', ['ぬりかべ', '間■仕■切■り', 'nurikabe', 'shading: nurikabe']],
	['futoshiki-nonconsecutive', ['futoshiki (nonconsecutive)']],
	['battlestars', ['battle stars']],
	['peggedtetrominoes', ['ペグオミノ']],
	['endpoints-iso', ['endpoints (iso)']],
	['statuepark', ['statue park']],
	['infection', ['数コロ', 'infection']],
	['arukone', ['アルコネ', 'arukone', 'paths: arukone']],
	['crackthecode', ['crack the code']],
	['dominosearch', ['ドミノ分割', 'domino division', 'domino search']],
	['magnets', ['マグネット', 'magnets']],
	['star-battleships', ['star battleships']],
	['arrowmaze', ['arrow maze', 'アローメイズ']],
	['findthematch', ['find the match']],
	['slovaksums', ['slovak sums']],
	['nurikabe-pairsums', ['nurikabe (pair sums)']],
	['fillomino-rectangles', ['fillomino rectangles', 'regions: fillomino rectangles']],
	['fillomino-offbyone', ['fillomino (off-by-one)']],
	['coral', ['coral']],
	['spiralgalaxies', ['天体ショー', 'spiral galaxies']],
	['meandering-wordsearch', ['meandering wordsearch']],
	['thermometers', ['thermometers']],
	['arithmeticalcity', ['arithmetical city']],
	['meanderingnumbers', ['にょろにょろナンバー', 'meandering numbers']],
	['meanderingwords', ['にょろにょろワード', 'meandering words']],
	['hideout-fences', ['hideout fences']],
	['towerdefense', ['tower defense']],
	['tetrominous-secondseen', ['tetrominous (second seen)']],
	['letterpairs', ['letter pairs']],
	['nuribou', ['ぬりぼう', 'nuribou']],
	['slitherlink-encoded', ['覆面スリザーリンク', 'slitherlink (encoded)']],
	['tigerinthewoods', ['tiger in the woods']],
	['sname', ['sname']],
	['hitori-diagonal', ['hitori (diagonal)']],
	['easyas-no2x2', ['easy as (no 2×2)']],
	['crisscross-tomtom', ['criss-cross (tomtom)']],
	['masyu', ['ましゅ', 'masyu']],
	['minesweeper-double', ['ダブル・ボンバーパズル', 'double minesweeper', 'minesweeper (double)']],
	['tapa', ['tapa', 'a. tapa']],
	['hitori', ['ひとりにしてくれ', 'hitori']],
	['battleships-iso', ['battleships (iso)']],
	['nurikabe-symmetric-encoded', ['symmetric encrypted nurikabe']],
	['skyscrapers-hex', ['skyscrapers (hex)', 'skyscrapers']],
	['summon', ['summon']],
	['crisscross', ['スケルトン', 'crisscross', 'criss-cross']],
	['railway', ['railway']],
	['fillomino-distinctshapes', ['fillomino (distinct shapes)']],
	['tapa-unknownscoupled', ['tapa (unknowns, coupled)']],
	['everysecondturn', ['every second turn']],
	['elasticbands', ['elastic bands']],
	['loop-dutch', ['loop (dutch)']],
	['shapesweeper-skyscrapers-connected', ['connected-shapesweeper-skyscrapers']],
	['fillomino-snake-encoded', ['cipher-fillomino-snake']],
	['coins-diagonal', ['coins (diagonal)']],
	['antidominosnakyloop', ['antidomino snaky loop']],
	['tetrominoes', ['テトロミノプレース']],
	['battleships-differentfleet', ['battleships (different fleet)']],
	['kuromasu', ['黒どこ', 'トラップサーチ', 'kuromasu']],
	['pyramidclimbers', ['pyramid climbers']],
	['shapeplacement', ['shape placement']],
	['doppelblock-set', ['doppelblock (set)', 'doppelblock (variable)']],
	['fillomino-encoded', ['fillomino (encoded)', 'fillomino (cipher)']],
	['neighbors', ['neighbors']],
	['boomerangs', ['boomerangs']],
	['arithmeticsquare-operations', ['arithmetic square operations']],
	['tents', ['ベストテントサイト', 'tents and trees', 'tents']],
	['endsum', ['エンドサム']]
]
